### ISSUE TITLE
What is the meaning of iterations?

### ISSUE THREAD

**Issue by Alexharrott** [songlab-cal/soapswga#11]
Hello, 

Thank you very much for publishing this swga2 tool. I have ran the programme with plasmodium and human genome, obtaining the below primer sets. 

FINAL TOP SETS FROM ALL RESTARTS: 10
[TGAACCTT, TTTTTTTTTTA], 441.92
[CAGGATTT, TTTTTTTTTTA], 434.71
[TGAACCTT, TTCGTTGG, TTTTTTTTTTA], 428.42
[CGTTGGAA, TGAACCTT, TTTTTTTTTTA], 426.06
[CAGGATTT, TTCGTTGG, TTTTTTTTTTA], 423.3
[CAGGATTT, CGTTGGAA, TTTTTTTTTTA], 420.8
[AGAGAGAT, TTCGTTGG, TTTTTTTTTTA], 415.96
[CGTTGGAA, GGGATTTC, TCGTTGGA, TTCGTTGG], 129.32
[CGTTGGAA, GGGATTTC, TCGTTGGA, TTCGTTGG], 129.32
[CAGGATTT, CGTTGGAA, TTCGTTGG], 122.84

There are not many primers in the sets, I am going to re-run with changing some of the parameters. I wondered if you could explain what iterations being 'number of iterations to run the primer set search; the maximum length of the resulting primer sets will be the number of iterations minus the number of drop iterations' means please? 

I left the iterations as 8, and the drop iterations as 4. My understanding is that the iterations variable is only applied in step 4? Does this mean that the maximum number of primers in a set will be 4 (8-4)? which is why I only have a maximum number of 4 primer sequences in a set. Thus if I change the variable to 18 and drop iterations to 2, ill obtain maximum of 16 primers in a set?

Thank you for your help and clarification with this.

**Comment by Alexharrott** [comment]
in addition, how does 'max sets' impact the primers? 

thank you.

**Comment by Alexharrott** [comment]
The parameter iterations just dictates how many times Algorithm 1 from [https://www.biorxiv.org/content/10.1101/2022.04.27.489632v1.full [biorxiv.org]](https://urldefense.proofpoint.com/v2/url?u=https-3A__www.biorxiv.org_content_10.1101_2022.04.27.489632v1.full&d=DwMGaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=jIaiWKKaJiIoQhWnIfXNNgMCuOtFqYXRVZYI0wotmyU&m=X6OHwpyE92Qks15JTpg66HmxZfzRKjCTNMwQioLaMsBbeg8pcuNn08P78VvF2ua0&s=v3m-i5monpB_R2tDxR_Lscs4kecfyhx63M1dCocgDzM&e=) should be repeated. This essentially limits how many total primers can be possibly added to a single primer set. 

Drop iterations dictates which iteration of the process to randomly eliminate a primer already added. This additional randomization helps explore the search space in case it is stuck in a local maxima. I wouldn’t worry too much about this parameter in practice though. You can probably leave it as is.

**Comment by Rohit-Satyam** [comment]
@Alexharrott what parameters did you end up using finally for plasmodium?
