### ISSUE TITLE
how to add path for Jellyfish

### ISSUE THREAD

**Issue by Milind-Mutnale** [songlab-cal/soapswga#2]
could you please explain how to add jellyfish to our path ???

**Comment by janeyubear** [comment]
Hi Milind,

Here are some simple directions for adding a directory to your path:
1. Open the .bash_profile or .bashrc file in your home directory (for example, /home/your-user-name/.bashrc) in a text editor.
2. Add export PATH="your-dir:$PATH" to the last line of the file, where your-dir is the directory you want to add.
3. Save the .bash_profile and .bashrc file.
4. Restart your terminal.
