### ISSUE TITLE
param-jason file

### ISSUE THREAD

**Issue by Milind-Mutnale** [songlab-cal/soapswga#3]
Hi, I am using this tool very recently and I found out that if I change the values in the param.jason files and run the analysis, the tool is ignoring the modified values and the analysis is being run on the default values. 

For example, I tried changing the max and min temperature values in the param.jason files, and when I run the command, I see that the values go back to default. Additionally, if I reopen the modified param.jason file, I see that modified values go back to default values. 

Hope you understood the issues here. 

Please check this issue

Thanks,
Milind

**Comment by janeyubear** [comment]
Hi Milind, I have updated the code to fix this. Can you download the latest version and run 'pip install .' again? Thank you!
