### ISSUE TITLE
What the meaning of the "FINAL TOP SETS FROM ALL RESTARTS"?

### ISSUE THREAD

**Issue by Ch3mmy** [songlab-cal/soapswga#4]
Hi, Tanks for you to publish this tools for sWGA!
I have confused about this results:
```
FINAL TOP SETS FROM ALL RESTARTS: 10
[AACGATAT, AATAACGA, ATAACGAA, ATAACGAT, ATTAATAATAA, TATAACGA], 11.25
[AACGATAT, AATAACGA, AATTAATAAT, ATAACGAT, TAACGAAT, TAACGATA], 9.97
[AACGATAT, AATAACGA, ATAACGAA, ATAACGAT, ATTAATAATAA, TAACGATA, TATAACGA], 9.78
[AATAACGA, ATTAATAATAA, GATAAATATA], 7.8
[AACGATAT, AATAACGA, AATTAATAATA, ATAACGAT, TAACGAAT, TAACGATA, TATAACGA], 7.51
[AATAACGA, ATAACGAT, ATTAATAATAA, GATAAATATA], 7.45
[AACGATAT, AATAACGA, AATTAATAAT, ATAACGAA, ATAACGAT, TAACGATA, TATAACGA], 7.33
[AACGATAT, AATAACGA, AATTAATAAT, ATAACGAA, ATAACGAT, TAACGATA, TATAACGA], 7.33
[AACGATAA, AACGATAT, AATAACGA, ATAACGAA, ATAACGAT, ATTAATAATAA, TATAACGA], 7.32
[ATTAATAATAA, GATAAATATA], 6.86
```
I got the different results of **FINAL TOP SETS FROM ALL RESTARTS** when I change the parameter```-w : maximum number of sets to build in parallel```
I want to know what the exactly meaning of the **maximum number of sets to build in parallel** and **Primer SET**
And The **Primer SET** can be straightly used for PCR？
Such as this primer set : ```[AACGATAT, AATAACGA, ATAACGAA, ATAACGAT, ATTAATAATAA, TATAACGA], 11.25 ``` 
I'm not sure that it means I can use this 6 primers for PCR ?And what is the 5' and 3‘ of the primer?
The primers in [one document](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5296604/) are shown below：

> pvset1 consists of the following 10 primers, with asterisks indicating phosphorothioate bonds that are necessary to prevent degradation by phi29: 5′-CGTTG*C*G-3′, 5′-TTTTTTC*G*C-3′, 5′-TCGTG*C*G-3′, 5′-CGTTTTTT*T*T-3′, 5′-TTTTTTTC*G*T-3′, 5′-CCGTT*C*G-3′, 5′-CGTTTC*G*T-3′, 5′-CGTTTC*G*C-3′, 5′-CGTTTT*C*G-3′, and 5′-TCGTTC*G*T-3′. pvset1920 consists of the following 12 primers: 5′-AACGAAGC*G*A-3′, 5′-ACGAAGCG*A*A-3′, 5′-ACGACGA*A*G-3′, 5′-ACGCGCA*A*C-3′, 5′-CAACGCG*G*T-3′, 5′-GACGAAA*C*G-3′, 5′-GCGAAAAA*G*G-3′, 5′-GCGAAGC*G*A-3′, 5′-GCGGAAC*G*A-3′, 5′-GCGTCGA*A*G-3′, 5′-GGTTAGCG*G*C-3′, and 5′-AACGAAT*C*G-3′.
>
Thanks a lot!😊

**Comment by janeyubear** [comment]
Hello,

Thank you for your questions! A larger value for 'maximum number of sets to build in parallel' may output more final top sets than a smaller value. This is because the primer sets are built primer by primer and the top w primer sets at each iteration continue to the next stage. 

Yes, each set from the final top sets is intended to be a candidate for PCR. They are ranked from highest to lowest based on the predicted scores (e.g., 11.25). The primers are always written in the 5' to 3' direction.

**Comment by Ch3mmy** [comment]
Thanks for your reply！It's useful！👍
I have one more question：There have another tools for swga: https://github.com/eclarke/swga
What is the different features between **soapswga** and **swga**？（I found the results of **swga** seems more detailed and many literature used **swga** generally）
For example, **swga** can get the results：

- Even binding site spacing in foreground genome

- Low total binding to background genome

The result shown as above is very important for SWGA.

I used to use the **swga** until I got a  error and the author of **swga** told me to use **soapswga**.
I want to know what's the different between them so that I can choose suitable one for my SWGA experiment.
Thank you！

**Comment by janeyubear** [comment]
Hi @chemy-cm, sorry for missing your issue. Please see the attached table for a list of the differences between swga and swga2.

With regard to your specific example, swga2 uses these features too (in addition to several others) to construct the final score, but currently does not output these intermediate values.

![Screen Shot 2022-10-01 at 2 35 31 PM](https://user-images.githubusercontent.com/14123568/193412120-e2d34224-1af2-4ad0-84dc-19f536d2d52d.png)

**Comment by Ch3mmy** [comment]
> Hi @chemy-cm, sorry for missing your issue. Please see the attached table for a list of the differences between swga and swga2.
> 
> With regard to your specific example, swga2 uses these features too (in addition to several others) to construct the final score, but currently does not output these intermediate values.
> 
> ![Screen Shot 2022-10-01 at 2 35 31 PM](https://user-images.githubusercontent.com/14123568/193412120-e2d34224-1af2-4ad0-84dc-19f536d2d52d.png)

Thanks a lot！It's useful for me 😁
