### ISSUE TITLE
How to optimize the parameter to get better results

### ISSUE THREAD

**Issue by Ch3mmy** [songlab-cal/soapswga#6]
Hi! I used this program recently. But the scores of final results seems very poor, **What can I change my parameter to get better results?**
My fg_genome: [Cryptosporidium parvum](https://cryptodb.org/common/downloads/Current_Release/CparvumIowaII/fasta/data/CryptoDB-59_CparvumIowaII_Genome.fasta) Gennome size : 9.1 Mb
My_bg_genome:[Human(GRCh38.p13)](https://uswest.ensembl.org/Homo_sapiens/Info/Index) Genome size :3000 Mb
And my **paramas.json** content:
###
    "json_file": "./params.json",
    "data_dir": "./",
    "src_dir": "/data/cm/software/soapswga-master/src/",
    "min_fg_freq": 2e-05,
    "max_bg_freq": 2e-06,
    "min_tm": 15,
    "max_tm": 45,
    "max_gini": 0.6,
    "max_primer": 500,
    "min_amp_pred": 5,
    "cpus": 30,
    "max_dimer_bp": 3,
    "max_self_dimer_bp": 4,
    "fg_genomes": [
        "/data/cm/soapswga/gemomes/Cpar_genome.fasta"
    ],
    "bg_genomes": [
        "/data/cm/soapswga/gemomes/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
    ],
    "fg_prefixes": [
        "./kmer_files/Cpar"
    ],
    "bg_prefixes": [
        "./kmer_files/Human"
    ],
    "mismatch_penalty": 4,
    "verbose": true,
    "drop_iterations": 4,
    "iterations": 8,
    "top_set_count": 10,
    "retries": 5,
    "max_sets": 5,
    "selection_metric": "deterministic",
    "fg_circular": false,
    "bg_circular": false,
    "fg_seq_lengths": [
        9152619
    ],
    "bg_seq_lengths": [
        3088286401
    ]

**The final results:**
```
FINAL TOP SETS FROM ALL RESTARTS: 10
[GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.97
[GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.92
[GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.92
[GTAGTAGTAGTA, TAGTAGTAGTAG], 5.74
[CTAAACCTAAA, GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.56
[CTAAACCTAAA, GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.56
[AGTAGTAGTAG, GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.32
[AGTAGTAGTAG, CTAAACCTAAA, GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.17
[AGTAGTAGTAG, CTAAACCTAAA, GTAGTAGTAGT, GTAGTAGTAGTA, TAAACCTAAAC, TAGTAGTAGTAG], 5.17
[CTAAACCTAAA, GTAGTAGTAGT, GTAGTAGTAGTA, TAGTAGTAGTAG], 5.14
```

**Comment by janeyubear** [comment]
Hi @chemy-cm, I would probably try to increase --max_sets from maybe 5 to 10. This will take longer but will for more possibilities. 

In terms of filtering out individual primer sequences, If you want to reduce the number of matches with the background you can decrease --max_bg_freq or if you want to increase the number of matches with the foreground you can increase --min_fg_freq. If evenness is important to you, you can modify --max_gini. These are just some examples that you can start with.
