### ISSUE TITLE
soapswga not available form current channels

### ISSUE THREAD

**Issue by Alexharrott** [songlab-cal/soapswga#7]
Hello, 

I keep getting an error when trying to install soapswga onto a lustre system. Please may I get some help with this. Thank you. 

When I follow the installation instructions, and install soapswga I get a channel error as shown below, even though I do have janedwivedi and conda-forge installed with python3.7.

_```
(base) ah31@farm5-head1:/lustre/scratch124/gsu/legacy/ah31/SWGA_FOLDER$ conda create -n SWGA2 python=3.7
(base) ah31@farm5-head1:/lustre/scratch124/gsu/legacy/ah31/SWGA_FOLDER$ conda activate SWGA2
(SWGA2) ah31@farm5-head1:/lustre/scratch124/gsu/legacy/ah31/SWGA_FOLDER$ conda install soapswga
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - soapswga

Current channels:

  - https://conda.anaconda.org/janedwivedi/linux-64
  - https://conda.anaconda.org/janedwivedi/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
 
To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```_


Thank you!

**Comment by scross92** [comment]
@Alexharrott were you able to get this resolved? Can you provide insight to how you fixed it.

**Comment by Alexharrott** [comment]
@scross92 hi, I updated my pip and python and cloned the GitHub rep. I think that made it work. Also to note the installation of the requirements.txt file threw me some errors too. I had to install numpy version 1.18.0 and scikit-learn v0.21.3 separately due to the order of the dependencies in the requirements file being installed. I hope this helps

**Comment by scross92** [comment]
Thanks @Alexharrott for the quick response. I will give this a try.
