### ISSUE TITLE
Step2_df.csv is empty

### ISSUE THREAD

**Issue by Rohit-Satyam** [songlab-cal/soapswga#8]
Hi @yss1 

I was trying to run `soapswga` on P falciparum genome with `GRch38 and Ralstonia Picketti` genome as background. However, I am unable to run `Step2` which terminates with the following error

```
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2077/rohit/miniconda/envs/swga2/bin/soapswga", line 5, in <module>
    from src.pipeline import main
  File "/ibex/scratch/projects/c2077/rohit/miniconda/envs/swga2/lib/python3.7/site-packages/src/pipeline.py", line 72, in <module>
    params = src.parameter.get_params(options)
  File "/ibex/scratch/projects/c2077/rohit/miniconda/envs/swga2/lib/python3.7/site-packages/src/parameter.py", line 95, in get_params
    os.makedirs(os.path.dirname(data['json_file']))
  File "/ibex/scratch/projects/c2077/rohit/miniconda/envs/swga2/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Can you help here?

**Comment by TGeneralovic** [comment]
I have a similar issue but with step 1. 

My json file looks like the following:

`{
    "json_file": "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/params3.json",
    "data_dir": "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/",
    "src_dir": "/home/tng23/rds/hpc-work/project_AH_SWJ/swga2-master/src",
    "min_fg_freq": 1e-05,
    "max_bg_freq": 5e-06,
    "min_tm": 15,
    "max_tm": 45,
    "max_gini": 0.6,
    "max_primer": 500,
    "min_amp_pred": 10,
    "cpus": 4,
    "max_dimer_bp": 3,
    "max_self_dimer_bp": 4,
    "fg_genomes": [
        "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/vivax/PlasmoDB-60_PvivaxP01_Genome.fasta"
    ],
    "bg_genomes": [
        "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/human/GRCh38_latest_genomic.fasta"
    ],
    "fg_prefixes": [
        "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/kmer_files/vivax"
    ],
    "bg_prefixes": [
        "/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/kmer_files/human"
    ],
    "mismatch_penalty": 4,
    "verbose": false,
    "drop_iterations": 4,
    "iterations": 8,
    "top_set_count": 10,
    "retries": 5,
    "max_sets": 12,
    "selection_metric": "deterministic",
    "fg_circular": false,
    "bg_circular": false,
    "fg_seq_lengths": [
        29040213
    ],
    "bg_seq_lengths": [
        3298430636
    ]
}`

and I am executing the step one job as so:
`soapswga step1 -j params3.json`

I am then met with the same error as the OP:
```
Traceback (most recent call last):
  File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/bin/soapswga", line 5, in <module>
    from src.pipeline import main
  File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/src/pipeline.py", line 72, in <module>
    params = src.parameter.get_params(options)
  File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/src/parameter.py", line 95, in get_params
    os.makedirs(os.path.dirname(data['json_file']))
  File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory:
```

I think there is some formatting error in our json files but after *many* cross-checks with an additional sanity check by copying over the example json and editing for my directory structure & inputs I repeatedly get the same error.

Maybe @Rohit-Satyam could you share your step1 json please and I can then see if I get the same error in step two as yourself.

**Comment by Alexharrott** [comment]
I have the same issue with 'file not found error' in step 1. @Rohit-Satyam are you able to share your step1json file please? Thank you all

**Comment by TGeneralovic** [comment]
My issue is now fixed, the full path to the json needs to be provided for it to be able to detect input 
e.g. `soapswga step1 -j /home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/params3.json`
This is the same for all steps (1-4)

In addition, which I missed in the README, the genome files require to have the same name as the prefix so changing 
`/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/vivax/PlasmoDB-60_PvivaxP01_Genome.fasta`
to 
`/home/tng23/rds/hpc-work/project_AH_SWJ/AH_run01/vivax/vivax.fasta `
for both the for and back.

Thanks for the tool!

**Comment by janeyubear** [comment]
Thanks @TGeneralovic and @Alexharrott for your help on this!
